# Dockerfile
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Set the environment to development
ENV NODE_ENV=development

# Command to run the app
CMD ["npm", "run", "start"]


# # Dockerfile
# FROM node:20-alpine

# # Set the working directory inside the container
# WORKDIR /app

# # Copy package.json and package-lock.json (if available)
# COPY package*.json ./

# # Install dependencies
# RUN npm install

# # Copy the rest of the application files
# COPY . .

# # Install nodemon
# RUN npm install -g nodemon

# # Command to run the app with nodemon
# CMD ["nodemon", "npm", "run", "start"]
